server:
  port: 8667 # 服务提供方

# 指定当前eureka客户端的注册地址,
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka,http://localhost:8999/eureka,http://localhost:8777/eureka

#当前服务名称
spring:
  application:
    name: eureka-service
